#!/bin/bash

BASE=$(dirname $0)
SCRIPTS="$BASE"/../scripts/
OUT=$(mktemp -d array_size-XXXXXX)

# This is x86-specific based on the command-line generated by the kernel's
# "make coccicheck V=1" output.
#
# Unfortunately, "make coccicheck MODE=patch COCCI=path/to/our.cocci" can't
# be used because it interleaves the patch output.

for i in $(cat "$BASE"/order.txt); do
	echo $i
	$SCRIPTS/super-spatch \
		--very-quiet \
		--cocci-file $BASE/$i.cocci \
		--dir . \
		-I ./arch/x86/include \
		-I ./arch/x86/include/generated \
		-I ./include \
		-I ./arch/x86/include/uapi \
		-I ./arch/x86/include/generated/uapi \
		-I ./include/uapi \
		-I ./include/generated/uapi \
		--include ./include/linux/kconfig.h \
		2>"$OUT"/$i.err | tee "$OUT"/$i.patch
	grep -v 'files match' "$OUT"/$i.err
	if [ -s "$OUT"/$i.patch ]; then
		patch -p1 < "$OUT"/$i.patch
		git commit -asm $i
	fi
done
rm -rf "$OUT"
